

---

spring:
  profiles: dev
  application:
    name: springcloud-config-yellowbean-dev
    
server:
  port: 6666

---

spring:
  profiles: test
  application:
    name: springcloud-config-yellowbean-test
    
server:
  port: 6677
