spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev
  application:
    name: springcloud-config-yellowbean-dev
    
server:
  port: 3356

---

spring:
  profiles: test
  application:
    name: springcloud-config-yellowbean-test
    
server:
  port: 3366
